##### VISUAL
cursor_shape beam

tab_bar_style powerline
tab_bar_edge top

# BEGIN_KITTY_FONTS
font_family      family=Lilex features="+ss01 +cv08 +cv11"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# BEGIN_KITTY_THEME
include themes/selene_abyss.conf
# END_KITTY_THEME

##### BINDS
# remove defaults
clear_all_shortcuts yes

## scrolling
map ctrl+up scroll_line_up
map ctrl+down scroll_line_down

map page_up scroll_page_up
map page_down scroll_page_down

map ctrl+home scroll_home
map ctrl+end scroll_end

## tabs
map ctrl+n new_tab
map ctrl+w close_tab

map ctrl+page_down next_tab
map ctrl+page_up previous_tab

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 goto_tab 10

## splits
map ctrl+\ new_window
map alt+w close_window

map ctrl+shift+left previous_window
map ctrl+shift+right next_window

map ctrl+alt+left move_window_backward
map ctrl+alt+right move_window_forward

map ctrl+1 first_window
map ctrl+2 second_window
map ctrl+3 third_window
map ctrl+4 fourth_window
map ctrl+5 fifth_window
map ctrl+6 sixth_window
map ctrl+7 seventh_window
map ctrl+8 eighth_window
map ctrl+9 ninth_window
map ctrl+0 tenth_window

## misc
# copy or interrupt
map ctrl+c copy_or_noop

map ctrl+comma edit_config_file
map alt+comma load_config_file
map f11 toggle_fullscreen
