preload=~/.config/hypr/wall_miku.jpg
preload=~/.config/hypr/wall_miku2.jpg
preload=~/.config/hypr/wall_veyle.jpg

wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/wall_miku.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = ~/.config/hypr/wall_miku2.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/wall_veyle.png
    fit_mode = cover
}

space = false
splash = false
ipc = off