input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.5)

    outer_color = rgb(66c8cc) rgb(a673d3) 45deg
    check_color = rgb(66c8cc) rgb(a673d3) 45deg
    fail_color = rgb(ff0000)

    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    rounding = 0

    position = 0, -20
    halign = center
    valign = center
}

background {
    monitor =
    path = ~/.config/hypr/lock_miku.jpg
    blur_passes = 0
    blur_size = 3
}
