# main
monitor=DP-3, 2560x1440@165Hz, 1920x0, 1

# terminal
workspace=1, monitor:DP-3, default:true

# zed
workspace=2, monitor:DP-3

# librewolf
workspace=3, monitor:DP-3

# vesktop
workspace=4, monitor:DP-3

# whatever
workspace=5, monitor:DP-3
workspace=6, monitor:DP-3
workspace=7, monitor:DP-3

# tv
monitor=HDMI-A-1, 3840x2160@30Hz, 0x0, 2
workspace=8, monitor:HDMI-A-1, default:true

# secondary
monitor=DP-1, 1920x1080@60Hz, 4480x0, 1

# kew
workspace=9, monitor:DP-1, default:true

# junk
workspace=10, monitor:DP-1, default:true
