# Main
monitor=DP-2, 2560x1440@164Hz, 0x0, 1

# Terminal
workspace=1, monitor:DP-2, default:true

# VSCode
workspace=2, monitor:DP-2

# Librewolf
workspace=3, monitor:DP-2

# Vesktop
workspace=4, monitor:DP-2

# Whatever
workspace=5, monitor:DP-2
workspace=6, monitor:DP-2
workspace=7, monitor:DP-2

# TV
monitor=HDMA-A-1, 3840x2160@30Hz, 2560x0, 1
workspace=8, monitor:HDMI-A-1, default:true

# Drawing tablet
monitor=DP-1, 1920x1080@60Hz, 2560x0, 1, transform, 2
workspace=9, monitor:DP-1, default:true
workspace=0, monitor:DP-1, default:true