windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# fsel should always be a centered popup
windowrule = match:class fsel, float true
windowrule = match:class fsel, size 400 800

windowrule = match:class clipboard_hist, float true
windowrule = match:class clipboard_hist, size 805 1000

windowrule = match:class logout_menu, float true
windowrule = match:class logout_menu, size 150 260

# Due to launcher, doesn't respect starting workspace
windowrule = workspace 4 silent, match:class vesktop

# Project Celosia
windowrule = workspace 5, fullscreen on, match:class Game