source = ~/.config/hypr/programs.conf

exec-once = waybar & \
    hyprpaper & \
    dunst & \
    systemctl --user start hyprpolkitagent & \
    vesktop & \
    cclipd -s 2 -t "image/png" -t "image/*" -t "text/plain;charset=utf-8" -t "text/*" -t "*"

exec-once = [workspace 1] $terminal
exec-once = [workspace 3 silent] $browser