source = ~/.config/hypr/programs.conf

exec-once = waybar & \
    hyprpaper & \
    dunst & \
    systemctl --user start hyprpolkitagent & \
    vesktop & \
    clipse -listen

exec-once = [workspace 1] $terminal
exec-once = [workspace 3 silent] $browser