source = ~/.config/hypr/programs.conf

exec-once = waybar & \
    hyprpaper & \
    hypridle & \
    dunst & \
    systemctl --user start hyprpolkitagent & \
    # kdeconnectd & \
    vesktop & \
    cclipd -c 100 -s 2 -t "image/png" -t "image/*" -t "text/plain;charset=utf-8" -t "text/*" -t "*"

exec-once = [workspace 1] $terminal
# exec-once = [workspace 2 silent] $editor
exec-once = [workspace 3 silent] $browser
exec-once = [workspace 4 silent] signal-desktop
# exec-once = [workspace 9 silent] $terminal --class kew -e kew
