source = ~/.config/hypr/hyprtoolkit.conf
source = ~/.config/hypr/programs.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/look_and_feel.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/windows_and_workspaces.conf

### Autostart
exec-once = waybar & \
    hyprpaper & \
    dunst & \
    systemctl --user start hyprpolkitagent & \
    [workspace 1] $terminal & \
    # [workspace 2 silent] $editor & \
    [workspace 3 silent] $browser & \
    vesktop & \
    # [workspace 9 silent] kitty --class kew -e kew & \
    clipse -listen


### Env
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

env = QT_QPA_PLATFORMTHEME,qt6ct

env = __GL_VRR_ALLOWED,0
env = __GL_GSYNC_ALLOWED,0
env = __GL_SYNC_TO_VBLANK,1

env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1